apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "rocketmq.broker.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: broker
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.broker.replicaCount }}
  podManagementPolicy: {{ .Values.broker.podManagementPolicy | quote }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.broker.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: broker
  serviceName: {{ include "rocketmq.broker.fullname" . }}
  {{- if .Values.broker.updateStrategy }}
  updateStrategy: {{- toYaml .Values.broker.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if .Values.broker.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.broker.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: broker
    spec:
     {{- include "rocketmq.imagePullSecrets" . | nindent 6 }}
      automountServiceAccountToken: {{ .Values.broker.automountServiceAccountToken }}
      {{- if .Values.broker.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.broker.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.broker.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.broker.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.broker.podAffinityPreset "component" "broker" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.broker.podAntiAffinityPreset "component" "broker" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.broker.nodeAffinityPreset.type "key" .Values.broker.nodeAffinityPreset.key "values" .Values.broker.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.broker.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.broker.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.broker.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.broker.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.broker.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.broker.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.broker.priorityClassName }}
      priorityClassName: {{ .Values.broker.priorityClassName }}
      {{- end }}
      {{- if .Values.broker.schedulerName }}
      schedulerName: {{ .Values.broker.schedulerName }}
      {{- end }}
      {{- if .Values.broker.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.broker.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: broker
          image: {{ include "rocketmq.image" .  }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.broker.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.broker.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          command: [ "/bin/sh" ]
          args: [ "-c", "./mqbroker -c /etc/rocketmq/$(POD_NAME)" ]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESRV_ADDR
              value: {{ include "rocketmq.broker.fullname" . }}:{{ .Values.broker.service.ports.broker }}
            - name: JAVA_OPT
              value: {{ .Values.broker.jvmOpt | quote }}
            {{- if .Values.broker.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.broker.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.broker.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.broker.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.broker.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.broker.extraEnvVarsSecret "context" $) }}
            {{- end }}
          ports:
            - name: broker
              containerPort: {{ .Values.broker.containerPorts.broker }}
              protocol: TCP
            {{- if .Values.broker.extraPorts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.broker.extraPorts "context" $) | nindent 12 }}
            {{- end }}
          startupProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 5
            successThreshold: 1
            tcpSocket:
              port: broker
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 5
            successThreshold: 1
            tcpSocket:
              port: broker
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 5
            successThreshold: 1
            tcpSocket:
              port: broker
          {{- if .Values.broker.resources }}
          resources: {{ toYaml .Values.broker.resources | nindent 12 }}
          {{- else if ne .Values.broker.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.broker.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/rocketmq/
            - name: data
              mountPath: {{ printf "%s/%s" (include "rocketmq.broker.storePathRootDir" .) "store" | replace "//" "/" }}
      volumes:
        {{- if or .Values.broker.configuration .Values.broker.existingConfigmap }}
        - name: config
          configMap:
            name: {{ include "rocketmq.broker.configmapName" . }}
        {{- else }}
        - name: config
          emptyDir: {}
        {{- end }}      
        {{- if and .Values.broker.persistence.enabled .Values.broker.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.broker.persistence.existingClaim . }}
        {{- else if not .Values.broker.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else if and .Values.broker.persistence.enabled (not .Values.broker.persistence.existingClaim) }}
  {{- if .Values.broker.persistentVolumeClaimRetentionPolicy.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.broker.persistentVolumeClaimRetentionPolicy.whenDeleted }}
    whenScaled: {{ .Values.broker.persistentVolumeClaimRetentionPolicy.whenScaled }}
  {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 10 }}
          app.kubernetes.io/component: broker
        {{- if or .Values.broker.persistence.annotations .Values.commonAnnotations }}
        {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list  .Values.broker.persistence.annotations .Values.commonAnnotations ) "context" . ) }}
        annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.broker.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.broker.persistence.size | quote }}
        {{- include "common.storage.class" (dict "persistence" .Values.broker.persistence "global" .Values.global) | nindent 8 }}
        {{- if .Values.broker.persistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.broker.persistence.selector "context" $) | nindent 10 }}
        {{- end -}}
  {{- end }}